apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.131.0.119"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: nodejs-mongodb-example
    openshift.io/deployment.name: nodejs-mongodb-example-1
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/scc: restricted
  creationTimestamp: "2020-01-09T18:44:03Z"
  generateName: nodejs-mongodb-example-1-
  labels:
    deployment: nodejs-mongodb-example-1
    deploymentconfig: nodejs-mongodb-example
    name: nodejs-mongodb-example
  name: nodejs-mongodb-example-1-stn6k
  namespace: jenkins
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: nodejs-mongodb-example-1
    uid: fd2ec4e4-330f-11ea-8f3b-022d2ba39bcf
  resourceVersion: "79705"
  selfLink: /api/v1/namespaces/jenkins/pods/nodejs-mongodb-example-1-stn6k
  uid: 01e8ccbf-3310-11ea-8f3b-022d2ba39bcf
spec:
  containers:
  - env:
    - name: DATABASE_SERVICE_NAME
      value: mongodb
    - name: MONGODB_USER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: nodejs-mongodb-example
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: nodejs-mongodb-example
    - name: MONGODB_DATABASE
      value: sampledb
    - name: MONGODB_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-admin-password
          name: nodejs-mongodb-example
    image: image-registry.openshift-image-registry.svc:5000/jenkins/nodejs-mongodb-example@sha256:9de899e168759647b3bd98cac5bd8c1b6cacad6b2dd19df627ee527dfa31c9ff
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    name: nodejs-mongodb-example
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000650000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-8hjwc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-7jmfk
  nodeName: ip-10-0-137-58.ec2.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000650000
    seLinuxOptions:
      level: s0:c26,c0
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-8hjwc
    secret:
      defaultMode: 420
      secretName: default-token-8hjwc
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-09T18:44:03Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-09T18:44:24Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-09T18:44:24Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-01-09T18:44:03Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://4691fa45eaa2de2f6a3dc2fc7c008b9948c8e6fc86a1d0346a0867540f68f3e4
    image: image-registry.openshift-image-registry.svc:5000/jenkins/nodejs-mongodb-example@sha256:9de899e168759647b3bd98cac5bd8c1b6cacad6b2dd19df627ee527dfa31c9ff
    imageID: image-registry.openshift-image-registry.svc:5000/jenkins/nodejs-mongodb-example@sha256:9de899e168759647b3bd98cac5bd8c1b6cacad6b2dd19df627ee527dfa31c9ff
    lastState: {}
    name: nodejs-mongodb-example
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-01-09T18:44:13Z"
  hostIP: 10.0.137.58
  phase: Running
  podIP: 10.131.0.119
  qosClass: Burstable
  startTime: "2020-01-09T18:44:03Z"
